# Generated by Claude Sonnet 4.6 (claude-sonnet-4-6)

import unittest

import numpy as np

from pyFOAM_hexBlockMesh.expansion_utils.SingleCell import (
	SingleCell2DGrid, Slice5D,
	getInteriorSlice, getInteriorEdgeSlice, getInteriorSurafceSlice5D
)
import pyFOAM_hexBlockMesh.geometry_utils.HexBlockVertices as HexBlockVertices


class TestSlice5D(unittest.TestCase) :

	def test_default_axes(self) :
		self.assertEqual(Slice5D().axes, [0, 1])

	def test_default_slices_length(self) :
		self.assertEqual(len(Slice5D().slices), 5)

	def test_default_slices_are_none(self) :
		for sl in Slice5D().slices :
			self.assertEqual(sl, slice(None))

	def test_isValid_default(self) :
		self.assertTrue(Slice5D().isValid())

	def test_isValid_with_int_local_vertex(self) :
		s = Slice5D()
		s.slices[2] = 0 ; s.slices[3] = -1 ; s.slices[4] = 0
		self.assertTrue(s.isValid())

	def test_isValid_wrong_axes_set(self) :
		s = Slice5D()
		s.axes = [0, 2]
		self.assertFalse(s.isValid())

	def test_isValid_duplicate_axes(self) :
		s = Slice5D()
		s.axes = [1, 1]
		self.assertFalse(s.isValid())

	def test_getArrayView_default_is_full_array(self) :
		arr = np.arange(48).reshape(3, 2, 2, 2, 2)
		np.testing.assert_array_equal(Slice5D().getArrayView(arr), arr)

	def test_getArrayView_fixes_local_vertex(self) :
		s = Slice5D()
		s.slices[2] = 0 ; s.slices[3] = 0 ; s.slices[4] = 0
		arr = np.zeros((3, 2, 2, 2, 2), dtype=int)
		arr[:, :, 0, 0, 0] = 7
		np.testing.assert_array_equal(s.getArrayView(arr), np.full((3, 2), 7))

	def test_getArrayView_swapped_axes_shape(self) :
		# axes=[1,0]: original axis-1 (size 2) → position 0,
		#             original axis-0 (size 3) → position 1
		s = Slice5D()
		s.axes = [1, 0]
		s.slices[2] = 0 ; s.slices[3] = 0 ; s.slices[4] = 0
		arr = np.zeros((3, 2, 2, 2, 2), dtype=int)
		self.assertEqual(s.getArrayView(arr).shape, (2, 3))

	def test_getArrayView_returns_writable_view(self) :
		arr = np.zeros((2, 3, 2, 2, 2), dtype=int)
		s = Slice5D()
		s.slices[2] = 0 ; s.slices[3] = 0 ; s.slices[4] = 0
		view = s.getArrayView(arr)
		view[:] = 5
		np.testing.assert_array_equal(arr[:, :, 0, 0, 0], np.full((2, 3), 5))


class TestGetInteriorSlice(unittest.TestCase) :
	'''
	Four cases from the match statement in getInteriorSlice:
	  (0, True)   → slice(1, None)      start of axis, forward
	  (-1, True)  → slice(0, -1)        end of axis, forward
	  (0, False)  → slice(-1, 0, -1)    start of axis, backward
	  (-1, False) → slice(-2, None, -1) end of axis, backward
	'''

	def _axis(self, v0, v1) :
		return HexBlockVertices.AxisProperties(v0, v1)

	def test_invalid_vertex_out_of_range(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSlice(8, self._axis(0, 1))

	def test_invalid_vertex_negative(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSlice(-1, self._axis(0, 1))

	def test_invalid_axis_type(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSlice(0, None)  # type: ignore[arg-type]

	def test_start_forward(self) :
		# v0 along axis-0 +: vertex_map[0][0]=0, orient=True
		self.assertEqual(getInteriorSlice(0, self._axis(0, 1)), slice(1, None))

	def test_end_forward(self) :
		# v1 along axis-0 +: vertex_map[1][0]=-1, orient=True
		self.assertEqual(getInteriorSlice(1, self._axis(0, 1)), slice(0, -1))

	def test_end_backward(self) :
		# v1 along axis-0 reversed: vertex_map[1][0]=-1, orient=False
		# Case (-1, False) → slice(-2, None, -1)
		self.assertEqual(getInteriorSlice(1, self._axis(1, 0)), slice(-2, None, -1))

	def test_start_backward(self) :
		# v0 along axis-0 reversed: vertex_map[0][0]=0, orient=False
		# Case (0, False) → slice(-1, 0, -1)
		self.assertEqual(getInteriorSlice(0, self._axis(1, 0)), slice(-1, 0, -1))


class TestGetInteriorEdgeSlice(unittest.TestCase) :
	'''
	Grid: SingleCell2DGrid(3, 2) → point_ID shape (3, 2, 2, 2, 2)

	edge (0→1): axis.dim=0 +, vertex_map[0]=(0,0,0)
	  slices=[slice(1,None), slice(None), 0, 0, 0], axes=[0,1]
	  view shape (n0-1, n1) = (2, 2)

	edge (0→3): axis.dim=1 +, vertex_map[0]=(0,0,0)
	  slices=[slice(None), slice(1,None), 0, 0, 0], axes=[0,1]
	  view shape (n0, n1-1) = (3, 1)

	edge (1→2): axis.dim=1 +, vertex_map[1]=(-1,0,0)
	  slices=[slice(None), slice(1,None), -1, 0, 0], axes=[0,1]
	  view shape (n0, n1-1) = (3, 1)
	'''

	def setUp(self) :
		self.grid = SingleCell2DGrid(3, 2)

	def test_invalid_vertex_out_of_range(self) :
		with self.assertRaises(AssertionError) :
			getInteriorEdgeSlice(8, HexBlockVertices.AxisProperties(0, 1))

	def test_invalid_vertex_negative(self) :
		with self.assertRaises(AssertionError) :
			getInteriorEdgeSlice(-1, HexBlockVertices.AxisProperties(0, 1))

	def test_invalid_axis_type(self) :
		with self.assertRaises(AssertionError) :
			getInteriorEdgeSlice(0, None)  # type: ignore[arg-type]

	def test_invalid_axis_dimension_2(self) :
		# axis.dimension == 2 (expansion axis) is not a cell-grid axis
		with self.assertRaises(AssertionError) :
			getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 4))

	def test_returns_valid_slice5d(self) :
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 1))
		self.assertIsInstance(s, Slice5D)
		self.assertTrue(s.isValid())

	def test_edge01_view_shape(self) :
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 1))
		self.assertEqual(s.getArrayView(self.grid.point_ID).shape, (2, 2))

	def test_edge03_view_shape(self) :
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 3))
		self.assertEqual(s.getArrayView(self.grid.point_ID).shape, (3, 1))

	def test_edge12_view_shape(self) :
		s = getInteriorEdgeSlice(1, HexBlockVertices.AxisProperties(1, 2))
		self.assertEqual(s.getArrayView(self.grid.point_ID).shape, (3, 1))

	def test_local_vertex_fixed_to_v0_coords(self) :
		# vertex_map[0] = (0, 0, 0) → slices[2]=0, [3]=0, [4]=0
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 1))
		self.assertEqual(s.slices[2], 0)
		self.assertEqual(s.slices[3], 0)
		self.assertEqual(s.slices[4], 0)

	def test_local_vertex_fixed_to_v1_coords(self) :
		# vertex_map[1] = (-1, 0, 0) → slices[2]=-1, [3]=0, [4]=0
		s = getInteriorEdgeSlice(1, HexBlockVertices.AxisProperties(0, 1))
		self.assertEqual(s.slices[2], -1)
		self.assertEqual(s.slices[3], 0)
		self.assertEqual(s.slices[4], 0)

	def test_interior_slice_on_correct_axis(self) :
		# axis.dim=0 → slices[0] is interior, slices[1] is all
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 1))
		self.assertEqual(s.slices[0], slice(1, None))
		self.assertEqual(s.slices[1], slice(None))

	def test_interior_slice_on_axis1(self) :
		# axis.dim=1 → slices[1] is interior, slices[0] is all
		s = getInteriorEdgeSlice(0, HexBlockVertices.AxisProperties(0, 3))
		self.assertEqual(s.slices[0], slice(None))
		self.assertEqual(s.slices[1], slice(1, None))


class TestGetInteriorSurfaceSlice5D(unittest.TestCase) :
	'''
	Valid call: vertex in range(8), exactly 2 AxisProperties with distinct
	dimensions both in {0, 1}.
	'''

	def _axes(self) :
		# Face (0,1,2,3): axes 0 and 1
		return HexBlockVertices.SurfaceProperties((0, 1, 2, 3)).axes

	def test_valid_call_returns_slice5d(self) :
		s = getInteriorSurafceSlice5D(0, self._axes())
		self.assertIsInstance(s, Slice5D)
		self.assertTrue(s.isValid())

	def test_invalid_vertex_out_of_range(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(8, self._axes())

	def test_invalid_vertex_negative(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(-1, self._axes())

	def test_invalid_axes_wrong_length(self) :
		ax = HexBlockVertices.AxisProperties(0, 1)
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(0, (ax,))  # only 1 axis

	def test_invalid_axes_wrong_type(self) :
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(0, (None, None))  # type: ignore[arg-type]

	def test_invalid_axes_dimension_2(self) :
		# axis (0→4) has dimension 2 — not a cell-grid axis
		ax0 = HexBlockVertices.AxisProperties(0, 1)  # dim=0
		ax2 = HexBlockVertices.AxisProperties(0, 4)  # dim=2
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(0, (ax0, ax2))

	def test_invalid_duplicate_dimensions(self) :
		ax0a = HexBlockVertices.AxisProperties(0, 1)  # dim=0
		ax0b = HexBlockVertices.AxisProperties(3, 2)  # dim=0
		with self.assertRaises(AssertionError) :
			getInteriorSurafceSlice5D(0, (ax0a, ax0b))


class TestSingleCell2DGrid_Init(unittest.TestCase) :

	def test_invalid_zero_n0(self) :
		with self.assertRaises(AssertionError) :
			SingleCell2DGrid(0, 3)

	def test_invalid_zero_n1(self) :
		with self.assertRaises(AssertionError) :
			SingleCell2DGrid(2, 0)

	def test_invalid_negative_n(self) :
		with self.assertRaises(AssertionError) :
			SingleCell2DGrid(-1, 3)

	def test_invalid_float_n(self) :
		with self.assertRaises(AssertionError) :
			SingleCell2DGrid(2.0, 3)  # type: ignore[arg-type]

	def test_cell_ID_shape(self) :
		grid = SingleCell2DGrid(2, 3)
		self.assertEqual(grid.cell_ID.shape, (2, 3))

	def test_point_ID_shape(self) :
		grid = SingleCell2DGrid(2, 3)
		self.assertEqual(grid.point_ID.shape, (2, 3, 2, 2, 2))

	def test_point_coordinates_shape(self) :
		grid = SingleCell2DGrid(2, 3)
		self.assertEqual(grid.point_coordinates.shape, (2, 3, 2, 2, 2, 3))

	def test_point_ID_sentinel(self) :
		# All point IDs must be initialised to -1 so the guard in setVertexPointID fires
		grid = SingleCell2DGrid(2, 3)
		np.testing.assert_array_equal(grid.point_ID, np.full((2, 3, 2, 2, 2), -1))

	def test_point_coordinates_zero(self) :
		grid = SingleCell2DGrid(2, 3)
		np.testing.assert_array_equal(grid.point_coordinates, np.zeros((2, 3, 2, 2, 2, 3)))


class TestSingleCell2DGrid_SetCellIDs(unittest.TestCase) :

	def test_fortran_ordering(self) :
		# Fortran order: axis-0 varies fastest
		# arange(0,6).reshape((2,3), order='F') = [[0,2,4],[1,3,5]]
		grid = SingleCell2DGrid(2, 3)
		grid.setCellIDs(start_ID=0)
		expected = np.array([[0, 2, 4], [1, 3, 5]])
		np.testing.assert_array_equal(grid.cell_ID, expected)

	def test_offset(self) :
		grid = SingleCell2DGrid(2, 3)
		grid.setCellIDs(start_ID=10)
		expected = np.array([[10, 12, 14], [11, 13, 15]])
		np.testing.assert_array_equal(grid.cell_ID, expected)

	def test_returns_next_start_ID(self) :
		grid = SingleCell2DGrid(2, 3)
		next_id = grid.setCellIDs(start_ID=5)
		self.assertEqual(next_id, 11)  # 5 + 2*3

	def test_invalid_negative(self) :
		grid = SingleCell2DGrid(2, 3)
		with self.assertRaises(AssertionError) :
			grid.setCellIDs(start_ID=-1)

	def test_invalid_type(self) :
		grid = SingleCell2DGrid(2, 3)
		with self.assertRaises(AssertionError) :
			grid.setCellIDs(start_ID=0.0)  # type: ignore[arg-type]


class TestSingleCell2DGrid_GetFaceShape(unittest.TestCase) :
	'''
	cell_shape = (n0, n1, 1) — the dummy third axis is always size 1.

	Face (0,3,2,1): v0->v1 along axis1, v1->v2 along axis0  → shape (n1, n0)
	Face (0,1,5,4): v0->v1 along axis0, v1->v2 along axis2  → shape (n0,  1)
	Face (0,4,7,3): v0->v1 along axis2, v1->v2 along axis1  → shape ( 1, n1)
	'''

	def setUp(self) :
		self.grid = SingleCell2DGrid(2, 3)

	def test_face_in_plane(self) :
		# Face (0,3,2,1): axes 1 and 0 → shape (n1, n0) = (3, 2)
		shape = self.grid.getFaceShape((0, 3, 2, 1))
		self.assertEqual(shape, (3, 2))

	def test_face_perpendicular_axis1(self) :
		# Face (0,1,5,4): axes 0 and 2 → shape (n0, 1) = (2, 1)
		shape = self.grid.getFaceShape((0, 1, 5, 4))
		self.assertEqual(shape, (2, 1))

	def test_face_perpendicular_axis0(self) :
		# Face (0,4,7,3): axes 2 and 1 → shape (1, n1) = (1, 3)
		shape = self.grid.getFaceShape((0, 4, 7, 3))
		self.assertEqual(shape, (1, 3))


class TestSingleCell2DGrid_GetSetPointIDs(unittest.TestCase) :
	'''
	Grid: SingleCell2DGrid(2, 3) → point_ID shape (2, 3, 2, 2, 2)

	getPointIDs / setPointIDs accept a Slice5D and operate on a view of point_ID.
	'''

	def setUp(self) :
		self.grid = SingleCell2DGrid(2, 3)

	def _corner_slice(self, vi=0, vj=0, vk=0) :
		'''Slice targeting local vertex (vi, vj, vk) for all cells.'''
		s = Slice5D()
		s.slices[2] = vi ; s.slices[3] = vj ; s.slices[4] = vk
		return s

	# ── corner slice (all cells, fixed local vertex) ──────────────────────────

	# ── input validation ──────────────────────────────────────────────────────

	def test_getPointIDs_invalid_slice_type(self) :
		with self.assertRaises(AssertionError) :
			self.grid.getPointIDs(None)  # type: ignore[arg-type]

	def test_setPointIDs_invalid_slice_type(self) :
		with self.assertRaises(AssertionError) :
			self.grid.setPointIDs(None, np.zeros((2, 3), dtype=int))  # type: ignore[arg-type]

	def test_setPointIDs_invalid_array_type(self) :
		with self.assertRaises(AssertionError) :
			self.grid.setPointIDs(self._corner_slice(), [[0, 1, 2], [3, 4, 5]])  # type: ignore[arg-type]

	def test_setPointIDs_invalid_float_dtype(self) :
		with self.assertRaises(AssertionError) :
			self.grid.setPointIDs(self._corner_slice(), np.zeros((2, 3), dtype=float))

	# ── correct behaviour ─────────────────────────────────────────────────────

	def test_set_get_v0_roundtrip(self) :
		s = self._corner_slice(0, 0, 0)
		ids = np.arange(6).reshape(2, 3)
		self.grid.setPointIDs(s, ids)
		np.testing.assert_array_equal(self.grid.getPointIDs(s), ids)

	def test_set_v0_lands_at_correct_array_position(self) :
		s = self._corner_slice(0, 0, 0)
		ids = np.arange(6).reshape(2, 3)
		self.grid.setPointIDs(s, ids)
		np.testing.assert_array_equal(self.grid.point_ID[:, :, 0, 0, 0], ids)

	def test_set_v0_does_not_clobber_v1(self) :
		# v1 local coords are (-1, 0, 0); must stay at sentinel
		s = self._corner_slice(0, 0, 0)
		self.grid.setPointIDs(s, np.arange(6).reshape(2, 3))
		np.testing.assert_array_equal(
			self.grid.point_ID[:, :, -1, 0, 0],
			np.full((2, 3), -1)
		)

	def test_different_local_vertices_independent(self) :
		# Setting v0 corner then v7 corner must not overlap
		s_v0 = self._corner_slice(0, 0, 0)
		s_v7 = self._corner_slice(0, -1, -1)
		self.grid.setPointIDs(s_v0, np.full((2, 3), 10))
		self.grid.setPointIDs(s_v7, np.full((2, 3), 20))
		np.testing.assert_array_equal(self.grid.point_ID[:, :, 0, 0, 0], np.full((2, 3), 10))
		np.testing.assert_array_equal(self.grid.point_ID[:, :, 0, -1, -1], np.full((2, 3), 20))

	# ── getPointIDs returns a writable view ───────────────────────────────────

	def test_get_returns_writable_view(self) :
		s = self._corner_slice(0, 0, 0)
		view = self.grid.getPointIDs(s)
		view[:] = 99
		np.testing.assert_array_equal(self.grid.point_ID[:, :, 0, 0, 0], np.full((2, 3), 99))

	# ── using getInteriorEdgeSlice ─────────────────────────────────────────────

	def test_edge_interior_roundtrip(self) :
		'''
		edge (0→1), v0-corner: interior view = point_ID[1:, :, 0, 0, 0]
		shape (n0-1, n1) = (1, 3) for this grid.
		'''
		axis = HexBlockVertices.AxisProperties(0, 1)
		s = getInteriorEdgeSlice(0, axis)
		ids = np.full((1, 3), 42)
		self.grid.setPointIDs(s, ids)
		np.testing.assert_array_equal(self.grid.getPointIDs(s), ids)

	def test_edge_interior_positions(self) :
		# edge (0→1) interior at v0-corner only touches row index 1
		axis = HexBlockVertices.AxisProperties(0, 1)
		s = getInteriorEdgeSlice(0, axis)
		self.grid.setPointIDs(s, np.full((1, 3), 42))
		np.testing.assert_array_equal(self.grid.point_ID[1, :, 0, 0, 0], [42, 42, 42])
		np.testing.assert_array_equal(self.grid.point_ID[0, :, 0, 0, 0], [-1, -1, -1])

	def test_two_vertex_edge_slices_independent(self) :
		'''
		Edge (0→1) gives interior slices at two different local vertex positions:
		  v0-corner: point_ID[1:, :, 0, 0, 0]   shape (1, 3)
		  v1-corner: point_ID[:-1, :, -1, 0, 0]  shape (1, 3)
		Setting each independently must not clobber the other.
		'''
		axis = HexBlockVertices.AxisProperties(0, 1)
		s_v0 = getInteriorEdgeSlice(0, axis)
		s_v1 = getInteriorEdgeSlice(1, axis)
		self.grid.setPointIDs(s_v0, np.full((1, 3), 10))
		self.grid.setPointIDs(s_v1, np.full((1, 3), 20))
		# v0-corner at row 1 unchanged by v1 write
		np.testing.assert_array_equal(self.grid.point_ID[1, :, 0, 0, 0], [10, 10, 10])
		# v1-corner at row 0
		np.testing.assert_array_equal(self.grid.point_ID[0, :, -1, 0, 0], [20, 20, 20])
		# v0-corner at row 0 untouched (sentinel)
		np.testing.assert_array_equal(self.grid.point_ID[0, :, 0, 0, 0], [-1, -1, -1])
		# v1-corner at row 1 untouched (sentinel)
		np.testing.assert_array_equal(self.grid.point_ID[1, :, -1, 0, 0], [-1, -1, -1])


if __name__ == '__main__' :

	unittest.main()
