# Generated by Claude Sonnet 4.6 (claude-sonnet-4-6)

import unittest

import numpy as np

from pyFOAM_hexBlockMesh.SchneiderExpansion import SchneiderExpansionLayer


class TestSchneiderExpansionLayer_Init(unittest.TestCase) :

	def test_invalid_n0_zero(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(0, 1)

	def test_invalid_n1_negative(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1, -1)

	def test_invalid_float_n0(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1.5, 1)

	def test_invalid_float_n1(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1, 2.0)

	def test_cells_base_shape(self) :
		# cells_base must be HexBlock(3*n0, 3*n1, 1)
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_base.cell_ID.shape, (6, 9, 1))

	def test_cells_base_shape_unit(self) :
		layer = SchneiderExpansionLayer(1, 1)
		self.assertEqual(layer.cells_base.cell_ID.shape, (3, 3, 1))

	def test_cells_hat_shape(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_hat.cell_ID.shape, (2, 3))

	def test_cells_hidden_shape(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_hidden.cell_ID.shape, (2, 3))

	def test_cells_lateral_count(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(len(layer.cells_lateral), 2)

	def test_cells_lateral_shapes(self) :
		layer = SchneiderExpansionLayer(2, 3)
		for grid in layer.cells_lateral :
			self.assertEqual(grid.cell_ID.shape, (2, 3))

	def test_cells_hat_point_ID_sentinel(self) :
		# All point IDs must be initialised to -1
		layer = SchneiderExpansionLayer(2, 3)
		np.testing.assert_array_equal(
			layer.cells_hat.point_ID,
			np.full((2, 3, 2, 2, 2), -1)
		)

	def test_cells_lateral_point_ID_sentinel(self) :
		layer = SchneiderExpansionLayer(2, 3)
		for grid in layer.cells_lateral :
			np.testing.assert_array_equal(
				grid.point_ID,
				np.full((2, 3, 2, 2, 2), -1)
			)


class TestSchneiderExpansionLayer_SetCellIDs(unittest.TestCase) :

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_returns_correct_next_id(self) :
		# cells_base: 6*9*1=54, hat: 6, hidden: 6, lateral[0]: 6, lateral[1]: 6 → 78
		next_id = self.layer.setCellIDs(start_ID=0)
		self.assertEqual(next_id, 78)

	def test_returns_correct_next_id_with_offset(self) :
		next_id = self.layer.setCellIDs(start_ID=10)
		self.assertEqual(next_id, 88)

	def test_cells_base_starts_at_offset(self) :
		self.layer.setCellIDs(start_ID=0)
		# Fortran order: [0,0,0] is first
		self.assertEqual(self.layer.cells_base.cell_ID[0, 0, 0], 0)

	def test_cells_base_last_id(self) :
		self.layer.setCellIDs(start_ID=0)
		self.assertEqual(self.layer.cells_base.cell_ID[-1, -1, -1], 53)

	def test_cells_hat_starts_after_base(self) :
		self.layer.setCellIDs(start_ID=0)
		# cells_hat[0,0] = first ID after cells_base (54)
		self.assertEqual(self.layer.cells_hat.cell_ID[0, 0], 54)

	def test_cells_hidden_starts_after_hat(self) :
		self.layer.setCellIDs(start_ID=0)
		# 54 + 6 = 60
		self.assertEqual(self.layer.cells_hidden.cell_ID[0, 0], 60)

	def test_cells_lateral0_starts_after_hidden(self) :
		self.layer.setCellIDs(start_ID=0)
		# 60 + 6 = 66
		self.assertEqual(self.layer.cells_lateral[0].cell_ID[0, 0], 66)

	def test_cells_lateral1_starts_after_lateral0(self) :
		self.layer.setCellIDs(start_ID=0)
		# 66 + 6 = 72
		self.assertEqual(self.layer.cells_lateral[1].cell_ID[0, 0], 72)

	def test_cells_hat_fortran_order(self) :
		self.layer.setCellIDs(start_ID=0)
		# arange(54, 60).reshape((2,3), order='F') = [[54,56,58],[55,57,59]]
		expected = np.array([[54, 56, 58], [55, 57, 59]])
		np.testing.assert_array_equal(self.layer.cells_hat.cell_ID, expected)


class TestSchneiderExpansionLayer_GetFaceShape(unittest.TestCase) :

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_base_face_delegates_to_cells_base(self) :
		# (0,3,2,1): all at ax2=0 → constant_axis=2, index=0 → cells_base
		result   = self.layer.getFaceShape((0, 3, 2, 1))
		expected = self.layer.cells_base.getFaceShape((0, 3, 2, 1))
		self.assertEqual(result, expected)

	def test_hat_face_delegates_to_cells_hat(self) :
		# (4,5,6,7): all at ax2=last → constant_axis=2, index=-1 → cells_hat
		result   = self.layer.getFaceShape((4, 5, 6, 7))
		expected = self.layer.cells_hat.getFaceShape((4, 5, 6, 7))
		self.assertEqual(result, expected)

	def test_hat_face_shape_values(self) :
		# cells_hat(2, 3): face (4,5,6,7) spans axes 0 and 1 → (n0, n1) = (2, 3)
		shape = self.layer.getFaceShape((4, 5, 6, 7))
		self.assertEqual(shape, (2, 3))

	def test_lateral_face_ax1_raises(self) :
		# (0,1,5,4): constant axis 1 → RuntimeError
		with self.assertRaises(RuntimeError) :
			self.layer.getFaceShape((0, 1, 5, 4))

	def test_lateral_face_ax0_raises(self) :
		# (0,4,7,3): constant axis 0 → RuntimeError
		with self.assertRaises(RuntimeError) :
			self.layer.getFaceShape((0, 4, 7, 3))

	def test_lateral_face_ax1_other_raises(self) :
		# (2,3,7,6): constant axis 1 → RuntimeError
		with self.assertRaises(RuntimeError) :
			self.layer.getFaceShape((2, 3, 7, 6))

	def test_lateral_face_ax0_other_raises(self) :
		# (1,2,6,5): constant axis 0 → RuntimeError
		with self.assertRaises(RuntimeError) :
			self.layer.getFaceShape((1, 2, 6, 5))


class TestSchneiderExpansionLayer_SetVertexPointID(unittest.TestCase) :
	'''
	vertex_map:
	  v0=(0,0,0), v1=(-1,0,0), v2=(-1,-1,0), v3=(0,-1,0)  → index[2]=0  (base only)
	  v4=(0,0,-1), v5=(-1,0,-1), v6=(-1,-1,-1), v7=(0,-1,-1) → index[2]=-1 (base + hat + lateral)

	cell_2D_grid_index = point_index[:2] + point_index
	  v4: (0,0)+(0,0,-1) = (0,0,0,0,-1)  → lateral[0] (point_index[1]=0)
	  v5: (-1,0)+(-1,0,-1) = (-1,0,-1,0,-1) → lateral[0]
	  v6: (-1,-1)+(-1,-1,-1) = (-1,-1,-1,-1,-1) → lateral[1] (point_index[1]=-1)
	  v7: (0,-1)+(0,-1,-1) = (0,-1,0,-1,-1) → lateral[1]
	'''

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	# --- base-layer vertices (0–3): only cells_base is touched ---

	def test_base_vertex_get_roundtrip(self) :
		self.layer.setVertexPointID(0, 42)
		self.assertEqual(self.layer.getVertexPointID(0), 42)

	def test_base_vertex_does_not_touch_cells_hat(self) :
		# v0 index in cells_hat would be (0,0,0,0,0); must stay -1
		self.layer.setVertexPointID(0, 42)
		self.assertEqual(self.layer.cells_hat.point_ID[0, 0, 0, 0, 0], -1)

	def test_base_vertex_does_not_touch_cells_lateral(self) :
		self.layer.setVertexPointID(0, 42)
		for grid in self.layer.cells_lateral :
			self.assertEqual(grid.point_ID[0, 0, 0, 0, 0], -1)

	# --- hat-layer vertices (4–7): cells_base + cells_hat + one cells_lateral ---

	def test_hat_vertex_v4_sets_cells_base(self) :
		self.layer.setVertexPointID(4, 55)
		self.assertEqual(self.layer.getVertexPointID(4), 55)

	def test_hat_vertex_v4_sets_cells_hat(self) :
		# v4=(0,0,-1) → cells_hat.point_ID[0,0,0,0,-1]
		self.layer.setVertexPointID(4, 55)
		self.assertEqual(self.layer.cells_hat.point_ID[0, 0, 0, 0, -1], 55)

	def test_hat_vertex_v4_sets_lateral0(self) :
		# v4: point_index[1]=0 → cells_lateral[0]
		self.layer.setVertexPointID(4, 55)
		self.assertEqual(self.layer.cells_lateral[0].point_ID[0, 0, 0, 0, -1], 55)

	def test_hat_vertex_v4_does_not_set_lateral1(self) :
		self.layer.setVertexPointID(4, 55)
		self.assertEqual(self.layer.cells_lateral[1].point_ID[0, 0, 0, 0, -1], -1)

	def test_hat_vertex_v5_sets_cells_hat(self) :
		# v5=(-1,0,-1) → cells_hat.point_ID[-1,0,-1,0,-1]
		self.layer.setVertexPointID(5, 66)
		self.assertEqual(self.layer.cells_hat.point_ID[-1, 0, -1, 0, -1], 66)

	def test_hat_vertex_v5_sets_lateral0(self) :
		# v5: point_index[1]=0 → cells_lateral[0]
		self.layer.setVertexPointID(5, 66)
		self.assertEqual(self.layer.cells_lateral[0].point_ID[-1, 0, -1, 0, -1], 66)

	def test_hat_vertex_v6_sets_cells_hat(self) :
		# v6=(-1,-1,-1) → cells_hat.point_ID[-1,-1,-1,-1,-1]
		self.layer.setVertexPointID(6, 77)
		self.assertEqual(self.layer.cells_hat.point_ID[-1, -1, -1, -1, -1], 77)

	def test_hat_vertex_v6_sets_lateral1(self) :
		# v6: point_index[1]=-1 → cells_lateral[1]
		self.layer.setVertexPointID(6, 77)
		self.assertEqual(self.layer.cells_lateral[1].point_ID[-1, -1, -1, -1, -1], 77)

	def test_hat_vertex_v6_does_not_set_lateral0(self) :
		self.layer.setVertexPointID(6, 77)
		self.assertEqual(self.layer.cells_lateral[0].point_ID[-1, -1, -1, -1, -1], -1)

	def test_hat_vertex_v7_sets_cells_hat(self) :
		# v7=(0,-1,-1) → cells_hat.point_ID[0,-1,0,-1,-1]
		self.layer.setVertexPointID(7, 88)
		self.assertEqual(self.layer.cells_hat.point_ID[0, -1, 0, -1, -1], 88)

	def test_hat_vertex_v7_sets_lateral1(self) :
		# v7: point_index[1]=-1 → cells_lateral[1]
		self.layer.setVertexPointID(7, 88)
		self.assertEqual(self.layer.cells_lateral[1].point_ID[0, -1, 0, -1, -1], 88)

	def test_hat_vertex_double_set_raises(self) :
		self.layer.setVertexPointID(4, 55)
		with self.assertRaises(AssertionError) :
			self.layer.setVertexPointID(4, 99)

	def test_all_base_vertices_independent(self) :
		for v in range(4) :
			self.layer.setVertexPointID(v, v * 10)
		for v in range(4) :
			self.assertEqual(self.layer.getVertexPointID(v), v * 10)

	def test_all_hat_vertices_set(self) :
		for v in range(4, 8) :
			self.layer.setVertexPointID(v, v * 10)
		for v in range(4, 8) :
			self.assertEqual(self.layer.getVertexPointID(v), v * 10)


class TestSchneiderExpansionLayer_GetEdgePointIDs(unittest.TestCase) :
	'''
	Edges where both vertices ∈ {0,1,2,3} or one vertex in each group
	must delegate to cells_base.
	'''

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_base_edge_0_1_delegates(self) :
		result   = self.layer.getEdgePointIDs(0, 1)
		expected = self.layer.cells_base.getEdgePointIDs(0, 1)
		np.testing.assert_array_equal(result, expected)

	def test_base_edge_1_0_reversed_delegates(self) :
		result   = self.layer.getEdgePointIDs(1, 0)
		expected = self.layer.cells_base.getEdgePointIDs(1, 0)
		np.testing.assert_array_equal(result, expected)

	def test_mixed_edge_0_4_delegates(self) :
		# One vertex in {0-3}, one in {4-7} → not a subset of {4-7} → cells_base
		result   = self.layer.getEdgePointIDs(0, 4)
		expected = self.layer.cells_base.getEdgePointIDs(0, 4)
		np.testing.assert_array_equal(result, expected)

	def test_base_edge_3_2_delegates(self) :
		result   = self.layer.getEdgePointIDs(3, 2)
		expected = self.layer.cells_base.getEdgePointIDs(3, 2)
		np.testing.assert_array_equal(result, expected)


class TestSchneiderExpansionLayer_SetEdgePointIDs(unittest.TestCase) :
	'''
	cells_base = HexBlock(6, 9, 1)  for n0=2, n1=3
	Interior edge points:
	  edge (0,1): axis 0, 5 points   edge (0,3): axis 1, 8 points
	  edge (0,4): axis 2, 0 points   (n2=1 → single layer expansion)

	Hat edges (both in {4,5,6,7}):
	  cells_hat:     v0-corner of cells [1:, col] = ids
	                 v1-corner of cells [:-1, col] = ids
	  cells_lateral: same slices in the appropriate lateral grid
	  cells_base:    macro-grid points (stride-3) = ids
	'''

	def setUp(self) :

		self.layer = SchneiderExpansionLayer(2, 3)

	# ------------------------------------------------------------------ #
	# Base / mixed edges: both-in-{0-3} or one-from-each-group           #
	# ------------------------------------------------------------------ #

	def test_base_edge_axis0_roundtrip(self) :
		# Edge (0,1): axis 0, 5 interior points
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 1), ids)

	def test_base_edge_axis0_reversed_roundtrip(self) :
		# Set (0,1), get (1,0) → interior points in reversed order
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(1, 0), ids[::-1])

	def test_base_edge_axis1_roundtrip(self) :
		# Edge (0,3): axis 1, 8 interior points
		ids = np.arange(100, 108)
		self.layer.setEdgePointIDs(0, 3, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 3), ids)

	def test_base_edge_axis2_empty_roundtrip(self) :
		# Edge (0,4): axis 2, n2-1=0 interior points (slab is 1-cell thick)
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(0, 4, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 4), ids)

	def test_base_edge_stored_in_cells_base(self) :
		# Verify the IDs actually land in cells_base (not just forwarded silently)
		ids = np.arange(8)
		self.layer.setEdgePointIDs(0, 3, ids)
		np.testing.assert_array_equal(
			self.layer.cells_base.getEdgePointIDs(0, 3), ids
		)

	def test_base_edge_does_not_touch_cells_hat(self) :
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID,
			np.full((2, 3, 2, 2, 2), -1)
		)

	def test_base_edge_does_not_touch_cells_lateral(self) :
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		for grid in self.layer.cells_lateral :
			np.testing.assert_array_equal(
				grid.point_ID,
				np.full((2, 3, 2, 2, 2), -1)
			)

	def test_mixed_edge_1_5_delegates(self) :
		# Edge (1,5): one vertex from each group → cells_base, axis 2, 0 points
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(1, 5, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(1, 5), ids)

	def test_mixed_edge_3_7_delegates(self) :
		# Edge (3,7): one vertex from each group → cells_base, axis 2, 0 points
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(3, 7, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(3, 7), ids)

	# ------------------------------------------------------------------ #
	# Hat edges: both in {4,5,6,7}                                       #
	# ------------------------------------------------------------------ #

	def test_hat_edge_4_5_no_error(self) :
		# Currently raises IndexError (6-element index on 5-D array)
		ids = np.array([42, ])
		self.layer.setEdgePointIDs(4, 5, ids)   # must not raise

	def test_hat_edge_4_5_cells_hat(self) :
		# Edge (4,5): axis 0, orientation +, n0-1=1 interior point
		# v4=(0,0,-1): cells_hat[1:, 0, 0, 0, -1] should equal ids
		# v5=(-1,0,-1): cells_hat[:-1, 0, -1, 0, -1] should equal ids
		ids = np.array([42])
		self.layer.setEdgePointIDs(4, 5, ids)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID[1:, 0, 0, 0, -1], ids
		)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID[:-1, 0, -1, 0, -1], ids
		)

	def test_hat_edge_4_5_cells_base(self) :
		# cells_base interior macro-point: slice(3,6,3)=[3] along axis 0,
		# first column, last axis-2 → cells_base.point_ID[3, 0, -1] = 42
		ids = np.array([42])
		self.layer.setEdgePointIDs(4, 5, ids)
		self.assertEqual(self.layer.cells_base.point_ID[3, 0, -1], 42)

	def test_hat_edge_4_5_cells_lateral0(self) :
		# v4: vertex_map[4][0]=0 → cells_lateral[0]
		# cells_lateral[0][1:, 0, 0, 0, -1] = ids
		ids = np.array([42])
		self.layer.setEdgePointIDs(4, 5, ids)
		np.testing.assert_array_equal(
			self.layer.cells_lateral[0].point_ID[1:, 0, 0, 0, -1], ids
		)

	def test_hat_edge_4_7_no_error(self) :
		# Edge (4,7): axis 1, n1-1=2 interior points
		ids = np.array([10, 11])
		self.layer.setEdgePointIDs(4, 7, ids)   # must not raise

	def test_hat_edge_4_7_cells_hat(self) :
		# v4=(0,0,-1): cells_hat[0, 1:, 0, 0, -1] = ids
		# v7=(0,-1,-1): cells_hat[0, :-1, 0, -1, -1] = ids
		ids = np.array([10, 11])
		self.layer.setEdgePointIDs(4, 7, ids)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID[0, 1:, 0, 0, -1], ids
		)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID[0, :-1, 0, -1, -1], ids
		)

	def test_hat_edge_5_6_no_error(self) :
		# Edge (5,6): axis 1, n1-1=2 interior points
		# v5=(-1,0,-1), v6=(-1,-1,-1)
		ids = np.array([20, 21])
		self.layer.setEdgePointIDs(5, 6, ids)   # must not raise

	def test_hat_edge_7_6_no_error(self) :
		# Edge (7,6): axis 0, n0-1=1 interior point
		# v7=(0,-1,-1), v6=(-1,-1,-1)
		ids = np.array([99])
		self.layer.setEdgePointIDs(7, 6, ids)   # must not raise


if __name__ == '__main__' :
	unittest.main()
