# Generated by Claude Sonnet 4.6 (claude-sonnet-4-6)

import unittest

import numpy as np

from pyFOAM_hexBlockMesh.SchneiderExpansion import SchneiderExpansionLayer


class TestSchneiderExpansionLayer_Init(unittest.TestCase) :

	def test_invalid_n0_zero(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(0, 1)

	def test_invalid_n1_negative(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1, -1)

	def test_invalid_float_n0(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1.5, 1)

	def test_invalid_float_n1(self) :
		with self.assertRaises(AssertionError) :
			SchneiderExpansionLayer(1, 2.0)

	def test_cells_base_shape(self) :
		# cells_base must be HexBlock(3*n0, 3*n1, 1)
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_base.cell_ID.shape, (6, 9, 1))

	def test_cells_base_shape_unit(self) :
		layer = SchneiderExpansionLayer(1, 1)
		self.assertEqual(layer.cells_base.cell_ID.shape, (3, 3, 1))

	def test_cells_hat_shape(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_hat.cell_ID.shape, (2, 3))

	def test_cells_hidden_shape(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(layer.cells_hidden.cell_ID.shape, (2, 3))

	def test_cells_lateral_count(self) :
		layer = SchneiderExpansionLayer(2, 3)
		self.assertEqual(len(layer.cells_lateral), 2)

	def test_cells_lateral_shapes(self) :
		layer = SchneiderExpansionLayer(2, 3)
		for grid in layer.cells_lateral :
			self.assertEqual(grid.cell_ID.shape, (2, 3))

	def test_cells_hat_point_ID_sentinel(self) :
		# All point IDs must be initialised to -1
		layer = SchneiderExpansionLayer(2, 3)
		np.testing.assert_array_equal(
			layer.cells_hat.point_ID,
			np.full((2, 3, 2, 2, 2), -1)
		)

	def test_cells_lateral_point_ID_sentinel(self) :
		layer = SchneiderExpansionLayer(2, 3)
		for grid in layer.cells_lateral :
			np.testing.assert_array_equal(
				grid.point_ID,
				np.full((2, 3, 2, 2, 2), -1)
			)


class TestSchneiderExpansionLayer_SetCellIDs(unittest.TestCase) :

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_returns_correct_next_id(self) :
		# cells_base: 6*9*1=54, hat: 6, hidden: 6, lateral[0]: 6, lateral[1]: 6 → 78
		next_id = self.layer.setCellIDs(start_ID=0)
		self.assertEqual(next_id, 78)

	def test_returns_correct_next_id_with_offset(self) :
		next_id = self.layer.setCellIDs(start_ID=10)
		self.assertEqual(next_id, 88)

	def test_cells_base_starts_at_offset(self) :
		self.layer.setCellIDs(start_ID=0)
		# Fortran order: [0,0,0] is first
		self.assertEqual(self.layer.cells_base.cell_ID[0, 0, 0], 0)

	def test_cells_base_last_id(self) :
		self.layer.setCellIDs(start_ID=0)
		self.assertEqual(self.layer.cells_base.cell_ID[-1, -1, -1], 53)

	def test_cells_hat_starts_after_base(self) :
		self.layer.setCellIDs(start_ID=0)
		# cells_hat[0,0] = first ID after cells_base (54)
		self.assertEqual(self.layer.cells_hat.cell_ID[0, 0], 54)

	def test_cells_hidden_starts_after_hat(self) :
		self.layer.setCellIDs(start_ID=0)
		# 54 + 6 = 60
		self.assertEqual(self.layer.cells_hidden.cell_ID[0, 0], 60)

	def test_cells_lateral0_starts_after_hidden(self) :
		self.layer.setCellIDs(start_ID=0)
		# 60 + 6 = 66
		self.assertEqual(self.layer.cells_lateral[0].cell_ID[0, 0], 66)

	def test_cells_lateral1_starts_after_lateral0(self) :
		self.layer.setCellIDs(start_ID=0)
		# 66 + 6 = 72
		self.assertEqual(self.layer.cells_lateral[1].cell_ID[0, 0], 72)

	def test_cells_hat_fortran_order(self) :
		self.layer.setCellIDs(start_ID=0)
		# arange(54, 60).reshape((2,3), order='F') = [[54,56,58],[55,57,59]]
		expected = np.array([[54, 56, 58], [55, 57, 59]])
		np.testing.assert_array_equal(self.layer.cells_hat.cell_ID, expected)


class TestSchneiderExpansionLayer_GetFaceShape(unittest.TestCase) :

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_base_face_delegates_to_cells_base(self) :
		# (0,3,2,1): all at ax2=0 → constant_axis=2, index=0 → cells_base
		result   = self.layer.getFaceShape((0, 3, 2, 1))
		expected = self.layer.cells_base.getFaceShape((0, 3, 2, 1))
		self.assertEqual(result, expected)

	def test_hat_face_delegates_to_cells_hat(self) :
		# (4,5,6,7): all at ax2=last → constant_axis=2, index=-1 → cells_hat
		result   = self.layer.getFaceShape((4, 5, 6, 7))
		expected = self.layer.cells_hat.getFaceShape((4, 5, 6, 7))
		self.assertEqual(result, expected)

	def test_hat_face_shape_values(self) :
		# cells_hat(2, 3): face (4,5,6,7) spans axes 0 and 1 → (n0, n1) = (2, 3)
		shape = self.layer.getFaceShape((4, 5, 6, 7))
		self.assertEqual(shape, (2, 3))

	def test_lateral_face_ax1_shape(self) :
		# (0,1,5,4): constant ax1, edges along ax0 and ax2
		# cells_hat.cell_shape = (n0, n1, 1) → shape (cell_shape[0], cell_shape[2]) = (n0, 1)
		shape = self.layer.getFaceShape((0, 1, 5, 4))
		self.assertEqual(shape, (2, 1))

	def test_lateral_face_ax0_shape(self) :
		# (0,4,7,3): constant ax0, edges along ax2 then ax1
		# cells_hat.cell_shape = (n0, n1, 1) → shape (cell_shape[2], cell_shape[1]) = (1, n1)
		shape = self.layer.getFaceShape((0, 4, 7, 3))
		self.assertEqual(shape, (1, 3))

	def test_lateral_face_ax1_other_shape(self) :
		# (2,3,7,6): constant ax1, edges along ax0 and ax2
		# cells_hat.cell_shape = (n0, n1, 1) → shape (cell_shape[0], cell_shape[2]) = (n0, 1)
		shape = self.layer.getFaceShape((2, 3, 7, 6))
		self.assertEqual(shape, (2, 1))

	def test_lateral_face_ax0_other_shape(self) :
		# (1,2,6,5): constant ax0, edges along ax1 then ax2
		# cells_hat.cell_shape = (n0, n1, 1) → shape (cell_shape[1], cell_shape[2]) = (n1, 1)
		shape = self.layer.getFaceShape((1, 2, 6, 5))
		self.assertEqual(shape, (3, 1))


class TestSchneiderExpansionLayer_SetVertexPointID(unittest.TestCase) :
	'''
	vertex_map:
	  v0=(0,0,0), v1=(-1,0,0), v2=(-1,-1,0), v3=(0,-1,0)  → index[2]=0  (base only)
	  v4=(0,0,-1), v5=(-1,0,-1), v6=(-1,-1,-1), v7=(0,-1,-1) → index[2]=-1 (base + hat + lateral)

	cell_2D_grid_index = point_index[:2] + point_index
	  v4: (0,0)+(0,0,-1) = (0,0,0,0,-1)  → lateral[0] (point_index[1]=0)
	  v5: (-1,0)+(-1,0,-1) = (-1,0,-1,0,-1) → lateral[0]
	  v6: (-1,-1)+(-1,-1,-1) = (-1,-1,-1,-1,-1) → lateral[1] (point_index[1]=-1)
	  v7: (0,-1)+(0,-1,-1) = (0,-1,0,-1,-1) → lateral[1]
	'''

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	# --- base-layer vertices (0–3): only cells_base is touched ---

	def test_base_vertex_get_roundtrip(self) :
		self.layer.setVertexPointID(0, 42)
		self.assertEqual(self.layer.getVertexPointID(0), 42)

	def test_base_vertex_does_not_touch_cells_hat(self) :
		# v0 index in cells_hat would be (0,0,0,0,0); must stay -1
		self.layer.setVertexPointID(0, 42)
		self.assertEqual(self.layer.cells_hat.point_ID[0, 0, 0, 0, 0], -1)

	def test_base_vertex_does_not_touch_cells_lateral(self) :
		self.layer.setVertexPointID(0, 42)
		for grid in self.layer.cells_lateral :
			self.assertEqual(grid.point_ID[0, 0, 0, 0, 0], -1)

	def test_hat_vertex_v4_sets_cells_base(self) :
		self.layer.setVertexPointID(4, 55)
		self.assertEqual(self.layer.getVertexPointID(4), 55)

	def test_hat_vertex_double_set_raises(self) :
		self.layer.setVertexPointID(4, 55)
		with self.assertRaises(AssertionError) :
			self.layer.setVertexPointID(4, 99)

	def test_all_base_vertices_independent(self) :
		for v in range(4) :
			self.layer.setVertexPointID(v, v * 10)
		for v in range(4) :
			self.assertEqual(self.layer.getVertexPointID(v), v * 10)

	def test_all_hat_vertices_set(self) :
		for v in range(4, 8) :
			self.layer.setVertexPointID(v, v * 10)
		for v in range(4, 8) :
			self.assertEqual(self.layer.getVertexPointID(v), v * 10)


class TestSchneiderExpansionLayer_GetEdgePointIDs(unittest.TestCase) :
	'''
	Edges where both vertices ∈ {0,1,2,3} or one vertex in each group
	must delegate to cells_base.
	'''

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)

	def test_base_edge_0_1_delegates(self) :
		result   = self.layer.getEdgePointIDs(0, 1)
		expected = self.layer.cells_base.getEdgePointIDs(0, 1)
		np.testing.assert_array_equal(result, expected)

	def test_base_edge_1_0_reversed_delegates(self) :
		result   = self.layer.getEdgePointIDs(1, 0)
		expected = self.layer.cells_base.getEdgePointIDs(1, 0)
		np.testing.assert_array_equal(result, expected)

	def test_mixed_edge_0_4_delegates(self) :
		# One vertex in {0-3}, one in {4-7} → not a subset of {4-7} → cells_base
		result   = self.layer.getEdgePointIDs(0, 4)
		expected = self.layer.cells_base.getEdgePointIDs(0, 4)
		np.testing.assert_array_equal(result, expected)

	def test_base_edge_3_2_delegates(self) :
		result   = self.layer.getEdgePointIDs(3, 2)
		expected = self.layer.cells_base.getEdgePointIDs(3, 2)
		np.testing.assert_array_equal(result, expected)


class TestSchneiderExpansionLayer_SetEdgePointIDs(unittest.TestCase) :
	'''
	cells_base = HexBlock(6, 9, 1)  for n0=2, n1=3
	Interior edge points:
	  edge (0,1): axis 0, 5 points   edge (0,3): axis 1, 8 points
	  edge (0,4): axis 2, 0 points   (n2=1 → single layer expansion)

	Hat edges (both in {4,5,6,7}):
	  cells_hat:     v0-corner of cells [1:, col] = ids
	                 v1-corner of cells [:-1, col] = ids
	  cells_lateral: same slices in the appropriate lateral grid
	  cells_base:    macro-grid points (stride-3) = ids
	'''

	def setUp(self) :

		self.layer = SchneiderExpansionLayer(2, 3)

	# ------------------------------------------------------------------ #
	# Base / mixed edges: both-in-{0-3} or one-from-each-group           #
	# ------------------------------------------------------------------ #

	def test_base_edge_axis0_roundtrip(self) :
		# Edge (0,1): axis 0, 5 interior points
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 1), ids)

	def test_base_edge_axis0_reversed_roundtrip(self) :
		# Set (0,1), get (1,0) → interior points in reversed order
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(1, 0), ids[::-1])

	def test_base_edge_axis1_roundtrip(self) :
		# Edge (0,3): axis 1, 8 interior points
		ids = np.arange(100, 108)
		self.layer.setEdgePointIDs(0, 3, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 3), ids)

	def test_base_edge_axis2_empty_roundtrip(self) :
		# Edge (0,4): axis 2, n2-1=0 interior points (slab is 1-cell thick)
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(0, 4, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(0, 4), ids)

	def test_base_edge_stored_in_cells_base(self) :
		# Verify the IDs actually land in cells_base (not just forwarded silently)
		ids = np.arange(8)
		self.layer.setEdgePointIDs(0, 3, ids)
		np.testing.assert_array_equal(
			self.layer.cells_base.getEdgePointIDs(0, 3), ids
		)

	def test_base_edge_does_not_touch_cells_hat(self) :
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		np.testing.assert_array_equal(
			self.layer.cells_hat.point_ID,
			np.full((2, 3, 2, 2, 2), -1)
		)

	def test_base_edge_does_not_touch_cells_lateral(self) :
		ids = np.arange(5)
		self.layer.setEdgePointIDs(0, 1, ids)
		for grid in self.layer.cells_lateral :
			np.testing.assert_array_equal(
				grid.point_ID,
				np.full((2, 3, 2, 2, 2), -1)
			)

	def test_mixed_edge_1_5_delegates(self) :
		# Edge (1,5): one vertex from each group → cells_base, axis 2, 0 points
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(1, 5, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(1, 5), ids)

	def test_mixed_edge_3_7_delegates(self) :
		# Edge (3,7): one vertex from each group → cells_base, axis 2, 0 points
		ids = np.array([], dtype=int)
		self.layer.setEdgePointIDs(3, 7, ids)
		np.testing.assert_array_equal(self.layer.getEdgePointIDs(3, 7), ids)


class TestSchneiderExpansionLayer_SetUpSingleCellGridPoints(unittest.TestCase) :
	'''
	cells_base = HexBlock(6, 9, 1) for n0=2, n1=3
	point_IDs = cells_base.point_ID[:, :, -1]  shape (7, 10)

	Filled with np.arange(70).reshape(7, 10) so point_IDs[i, j] = i + 7*j

	Index sets used by the method
	  axis-0 (7 elements): 1::3=[1,4]  2::3=[2,5]  :-1:3=[0,3]  3::3=[3,6]
	  axis-1 (10 elements): :-1:3=[0,3,6]  3::3=[3,6,9]  1::3=[1,4,7]  2::3=[2,5,8]
	'''

	def setUp(self) :
		self.layer = SchneiderExpansionLayer(2, 3)
		self.layer.cells_base.point_ID[:, :, -1] = np.arange(70).reshape(7, 10)
		self.layer.setUpSingleCellGridPoints()

	# ------------------------------------------------------------------ #
	# cells_hat — 8 vertex positions                                     #
	# ------------------------------------------------------------------ #

	def test_cells_hat_v000(self) :
		# point_IDs[1::3, :-1:3] → rows [1,4], cols [0,3,6]
		expected = np.array([[10, 13, 16], [40, 43, 46]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 0, 0, 0], expected)

	def test_cells_hat_v100(self) :
		# point_IDs[2::3, :-1:3] → rows [2,5], cols [0,3,6]
		expected = np.array([[20, 23, 26], [50, 53, 56]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 1, 0, 0], expected)

	def test_cells_hat_v010(self) :
		# point_IDs[1::3, 3::3] → rows [1,4], cols [3,6,9]
		expected = np.array([[13, 16, 19], [43, 46, 49]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 0, 1, 0], expected)

	def test_cells_hat_v110(self) :
		# point_IDs[2::3, 3::3] → rows [2,5], cols [3,6,9]
		expected = np.array([[23, 26, 29], [53, 56, 59]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 1, 1, 0], expected)

	def test_cells_hat_v001(self) :
		# point_IDs[:-1:3, :-1:3] → rows [0,3], cols [0,3,6]
		expected = np.array([[0, 3, 6], [30, 33, 36]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 0, 0, 1], expected)

	def test_cells_hat_v101(self) :
		# point_IDs[3::3, :-1:3] → rows [3,6], cols [0,3,6]
		expected = np.array([[30, 33, 36], [60, 63, 66]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 1, 0, 1], expected)

	def test_cells_hat_v011(self) :
		# point_IDs[:-1:3, 3::3] → rows [0,3], cols [3,6,9]
		expected = np.array([[3, 6, 9], [33, 36, 39]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 0, 1, 1], expected)

	def test_cells_hat_v111(self) :
		# point_IDs[3::3, 3::3] → rows [3,6], cols [3,6,9]
		expected = np.array([[33, 36, 39], [63, 66, 69]])
		np.testing.assert_array_equal(self.layer.cells_hat.point_ID[:, :, 1, 1, 1], expected)

	# ------------------------------------------------------------------ #
	# cells_hidden — final state (lines 69-71 overwrite lines 65-67)     #
	# ------------------------------------------------------------------ #

	def test_cells_hidden_v000(self) :
		# point_IDs[1::3, 1::3] → rows [1,4], cols [1,4,7]  (not overwritten)
		expected = np.array([[11, 14, 17], [41, 44, 47]])
		np.testing.assert_array_equal(self.layer.cells_hidden.point_ID[:, :, 0, 0, 0], expected)

	def test_cells_hidden_v100_overwritten(self) :
		# line 65 (rows[2,5], cols[1,4,7]) overwritten by line 69 (rows[2,5], cols[0,3,6])
		expected = np.array([[20, 23, 26], [50, 53, 56]])
		np.testing.assert_array_equal(self.layer.cells_hidden.point_ID[:, :, 1, 0, 0], expected)

	def test_cells_hidden_v010_overwritten(self) :
		# line 66 (rows[1,4], cols[2,5,8]) overwritten by line 70 (rows[1,4], cols[3,6,9])
		expected = np.array([[13, 16, 19], [43, 46, 49]])
		np.testing.assert_array_equal(self.layer.cells_hidden.point_ID[:, :, 0, 1, 0], expected)

	def test_cells_hidden_v110_overwritten(self) :
		# line 67 (rows[2,5], cols[2,5,8]) overwritten by line 71 (rows[2,5], cols[3,6,9])
		expected = np.array([[23, 26, 29], [53, 56, 59]])
		np.testing.assert_array_equal(self.layer.cells_hidden.point_ID[:, :, 1, 1, 0], expected)

	def test_cells_hidden_v001(self) :
		# point_IDs[1::3, :-1:3] → rows [1,4], cols [0,3,6]
		expected = np.array([[10, 13, 16], [40, 43, 46]])
		np.testing.assert_array_equal(self.layer.cells_hidden.point_ID[:, :, 0, 0, 1], expected)

	def test_cells_hidden_v101_v011_v111_unset(self) :
		# These three vertex positions are never assigned by setUpSingleCellGridPoints
		for idx in [(1, 0, 1), (0, 1, 1), (1, 1, 1)] :
			np.testing.assert_array_equal(
				self.layer.cells_hidden.point_ID[:, :, idx[0], idx[1], idx[2]],
				np.full((2, 3), -1),
				err_msg=f'vertex {idx} should remain -1'
			)

	# ------------------------------------------------------------------ #
	# cells_lateral[0]                                                   #
	# ------------------------------------------------------------------ #

	def test_cells_lateral0_v000(self) :
		# point_IDs[:-1:3, 1::3] → rows [0,3], cols [1,4,7]
		expected = np.array([[1, 4, 7], [31, 34, 37]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 0, 0, 0], expected)

	def test_cells_lateral0_v100(self) :
		# point_IDs[1::3, 1::3] → rows [1,4], cols [1,4,7]
		expected = np.array([[11, 14, 17], [41, 44, 47]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 1, 0, 0], expected)

	def test_cells_lateral0_v010(self) :
		# point_IDs[:-1:3, 2::3] → rows [0,3], cols [2,5,8]
		expected = np.array([[2, 5, 8], [32, 35, 38]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 0, 1, 0], expected)

	def test_cells_lateral0_v110(self) :
		# point_IDs[1::3, 1::3] → rows [1,4], cols [1,4,7]  (same source as v100)
		expected = np.array([[11, 14, 17], [41, 44, 47]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 1, 1, 0], expected)

	def test_cells_lateral0_v001(self) :
		# point_IDs[:-1:3, :-1:3] → rows [0,3], cols [0,3,6]
		expected = np.array([[0, 3, 6], [30, 33, 36]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 0, 0, 1], expected)

	def test_cells_lateral0_v101(self) :
		# point_IDs[1::3, :-1:3] → rows [1,4], cols [0,3,6]
		expected = np.array([[10, 13, 16], [40, 43, 46]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 1, 0, 1], expected)

	def test_cells_lateral0_v011(self) :
		# point_IDs[:-1:3, 3::3] → rows [0,3], cols [3,6,9]
		expected = np.array([[3, 6, 9], [33, 36, 39]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 0, 1, 1], expected)

	def test_cells_lateral0_v111(self) :
		# point_IDs[1::3, 3::3] → rows [1,4], cols [3,6,9]
		expected = np.array([[13, 16, 19], [43, 46, 49]])
		np.testing.assert_array_equal(self.layer.cells_lateral[0].point_ID[:, :, 1, 1, 1], expected)

	# ------------------------------------------------------------------ #
	# cells_lateral[1]                                                   #
	# ------------------------------------------------------------------ #

	def test_cells_lateral1_v000(self) :
		# point_IDs[2::3, 1::3] → rows [2,5], cols [1,4,7]
		expected = np.array([[21, 24, 27], [51, 54, 57]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 0, 0, 0], expected)

	def test_cells_lateral1_v100(self) :
		# point_IDs[3::3, 1::3] → rows [3,6], cols [1,4,7]
		expected = np.array([[31, 34, 37], [61, 64, 67]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 1, 0, 0], expected)

	def test_cells_lateral1_v010(self) :
		# point_IDs[2::3, 2::3] → rows [2,5], cols [2,5,8]
		expected = np.array([[22, 25, 28], [52, 55, 58]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 0, 1, 0], expected)

	def test_cells_lateral1_v110(self) :
		# point_IDs[3::3, 1::3] → rows [3,6], cols [1,4,7]  (same source as v100)
		expected = np.array([[31, 34, 37], [61, 64, 67]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 1, 1, 0], expected)

	def test_cells_lateral1_v001(self) :
		# point_IDs[2::3, :-1:3] → rows [2,5], cols [0,3,6]
		expected = np.array([[20, 23, 26], [50, 53, 56]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 0, 0, 1], expected)

	def test_cells_lateral1_v101(self) :
		# point_IDs[3::3, :-1:3] → rows [3,6], cols [0,3,6]
		expected = np.array([[30, 33, 36], [60, 63, 66]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 1, 0, 1], expected)

	def test_cells_lateral1_v011(self) :
		# point_IDs[2::3, 3::3] → rows [2,5], cols [3,6,9]
		expected = np.array([[23, 26, 29], [53, 56, 59]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 0, 1, 1], expected)

	def test_cells_lateral1_v111(self) :
		# point_IDs[3::3, 3::3] → rows [3,6], cols [3,6,9]
		expected = np.array([[33, 36, 39], [63, 66, 69]])
		np.testing.assert_array_equal(self.layer.cells_lateral[1].point_ID[:, :, 1, 1, 1], expected)


if __name__ == '__main__' :
	unittest.main()
